#
# Makefile for the access methods module
#
# src/backend/access/mybuffer/Makefile
#

subdir = src/backend/access/mybuffer
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = mybuffer.o

include $(top_srcdir)/src/backend/common.mk
